services:
  bts:
    build: .
    ports:
      - "4000:4000"
      - "4433:4433"
    volumes:
      - ../bup:/bts/static/bup/dev
      - ./data:/bts/data
      - ./certs:/bts/certs
      - ./config.json:/bts/config.json
    restart: unless-stopped
